### ISSUE TITLE
adding interpolation_type argument for `imresize`

### ISSUE THREAD

**Issue by ekinakyurek** [JuliaImages/ImageTransformations.jl#51]
It would be great if someone adds interpolation_type argument in `imresize` function as in [PIL](
https://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.resize) package of Python.

**Comment by Evizero** [comment]
ref: https://github.com/JuliaImages/Images.jl/issues/69#issuecomment-408981473

**Comment by johnnychen94** [comment]
I'll put some codes here using `AbstractInterpolation` for this purpose, as you mentioned in [JuliaImages/Images.jl#69 (comment)](
https://github.com/JuliaImages/Images.jl/issues/69#issuecomment-408981473). BTW I like the idea of using `AbstractInterpolation` since it gives more flexibility than keyword argument.

**Comment by andrew-saydjari** [comment]
I tried following the comment above for imrotate by

`using Interpolations
imrotate(img,1.2,Lanczos4OpenCV())
`

but receive a message error. Am I making some simple mistake?

**Comment by johnnychen94** [comment]
Now supported by #115

```julia
imresize(img, (128, 128); method=Linear())
```
