### ISSUE TITLE
imresize throw StackOverflowError with sz of array type

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/ImageTransformations.jl#57]
reported by @johnnychen94 at https://github.com/JuliaImages/Images.jl/issues/742

> The document of `imresize` doesn't say sz must be `Tuple` type, so I just try the MATLAB way of using `imresize`, and it throws an unexpected StackOverflowError.
>
>```julia
>using Images, TestImages
>lena = testimage("lena_gray_256")
>
>imresize(lena, (128,128)) # work as expected
>imresize(lena, [128,128]) # throw StackOverflowError
>```

**Comment by johnnychen94** [comment]
Update:

The document of `imresize` doesn't say sz must be `Tuple{Vararg{Integer}}` type, so I just try the MATLAB way of using `imresize`, and it throws an unexpected StackOverflowError. 
  * use `[128,128]` as size, it's `Array` type.
  * use `ceil.(size(img) .* 0.5)` as size, it is `Tuple{Float64,Float64}` Type

```julia
using Images, TestImages
lena = testimage("lena_gray_256")

imresize(lena, (128, 128)) # work as expected
imresize(lena, [128, 128]) # throw StackOverflowError
imresize(lena, (128.0, 128.0)) # throw StackOverflowError
```

With a temporary solution, just use
```julia
using Images, TestImages
lena = testimage("lena_gray_256")

imresize(lena, (128, 128)) # work as expected
imresize(lena, ceil.(Int, size(lena) .* 0.5)) # work as expected
```

Also,
can we add an `imresize(img, ratio)` API support to this function just like MATLAB? Since Images are always at least 2D, there will be no ambiguity. I think it might be fairly easy to implement.
```julia
imresize(original::AbstractArray, dim1, dimN...) = imresize(original, (dim1,dimN...)) 
imresize(original::AbstractArray, ratio) = imresize(original, round.(Int, size(original).* ratio) # add this line of code
```

**Comment by Evizero** [comment]
Thanks for the thorough report. I agree the current situation is suboptimal. I also like the ratio idea

**Comment by timholy** [comment]
:+1: , thanks indeed @johnnychen94.

But we should use a keyword argument for `ratio`. Otherwise it has ambiguous intent for one-dimensional "images." (JuliaImages has a much firmer commitment to providing good support for images of arbitrary dimensionality than does Matlab.) Or we could use `Percent` but I think a keyword argument would be better.
