### ISSUE TITLE
`restrict` not preserving image colortype

### ISSUE THREAD

**Issue by IanButterworth** [JuliaImages/ImageTransformations.jl#68]
I'm trying to convert a `RGB{N0f8}` image to the YUV420 format for ffmpeg. (YUV420 is YCbCr, where the Cb and Cr channels are half resolution)

When trying to use restrict to downsample YCbCr{Float64} the result is RGB{Float64}.

```julia
img = rand(RGB{N0f8},100,200)
img_YCbCr = convert.(YCbCr{Float64}, img)
@show typeof(img_YCbCr) #Array{YCbCr{Float64},2}

img_YCbCr_half = restrict(img_YCbCr)
@show typeof(img_YCbCr_half) #Array{RGB{Float64},2}
```

Also, is there a better way to do RGB{N0f8} -> YUV420 (UInt8)

**Comment by ianshmean** [comment]
Moving where the restrict happens solves the issue, but I'm not sure that it would be considered a true RGB->YUV420 conversion in that case:
```julia
img = rand(RGB{N0f8},100,200)
img_YCbCr = convert.(YCbCr{Float64}, img)
img_YCbCr_half = convert.(YCbCr{Float64}, restrict(img))
```

**Comment by johnnychen94** [comment]
Thanks for the report, I agree that we need to preserve the types for consistency. I guess we can achieve this by enhancing 

https://github.com/JuliaImages/ImageTransformations.jl/blob/83cdcea87e270bd2179b5e2ad6e141aee8110835/src/resizing.jl#L27-L34

But it might require some time to check the details. I can fix it as part of my GSoC project since this's not urgent.

---

> is there a better way to do RGB{N0f8} -> YUV420 (UInt8)

N0f8(aka `Normed{UInt8, 8}`) can be treated as UInt8, so you don't need to change the storage type; color conversion is sufficient. Also, `rawview(channelview(img))` might give what you want.

> I'm not sure that it would be considered a true RGB->YUV420 conversion in that case

RGB -> YUV420: https://github.com/JuliaGraphics/Colors.jl/blob/master/src/conversions.jl#L762-L767
YUV420 -> RGB: https://github.com/JuliaGraphics/Colors.jl/blob/master/src/conversions.jl#L156-L164

Do I understand your questions well?

**Comment by ianshmean** [comment]
Great! My fix is ok for me for now, so not urgent.

As for the RGB -> YUV420 code, that technically does RGB -> YCbCr aka YUV. 
YUV420 has half resolution Cb (U) and Cr (V) planes, hence the need for restrict on those planes.

It may be helpful to expand the RGB -> YUV conversions to support the different standard image/video plane compression standards, like YUV420, YUV422: https://ffmpeg.org/doxygen/4.1/pixfmt_8h.html especially given VideoIO is soon to support video encoding through ffmpeg

**Comment by johnnychen94** [comment]
In that case, I think we can introduce non-parametric colorants alongside with some conversion utils in `ColorTypes.jl`, just like [`RGB24`](https://github.com/JuliaGraphics/ColorTypes.jl/blob/0d5904e19b41227938274d325886dff221a8e8d7/src/types.jl#L278-L292).

I'm not familiar with these color formats, so you might need to do it yourself. I think @timholy would be happy to review it. 😄

**Comment by timholy** [comment]
Fixing this is more subtle than it may seem. The issue: math isn't defined on `YCbCr`, because the components of this color space do not form a vector space:
```julia
RGB{Float32}(0.4549476f0,0.8344852f0,0.03976333f0)

julia> c2 = rand(RGB{Float32})
RGB{Float32}(0.82011116f0,0.48564684f0,0.75434136f0)

julia> z1 = convert(YCbCr, c1+c2)
YCbCr{Float32}(229.85962f0,104.93973f0,131.75018f0)

julia> convert(YCbCr, c1).cb + convert(YCbCr, c2).cb
198.78857f0

julia> z1.cb
104.93973f0
```
(Technically that's true of RGB as well, but it's commonplace to ignore that. See the README of [ColorVectorSpace](https://github.com/JuliaGraphics/ColorVectorSpace.jl) for more info.)

`restrict` [accumulates its output](https://github.com/JuliaImages/ImageTransformations.jl/blob/7a5d9ae537f4158757fbcb70aac7f91e495d635e/src/resizing.jl#L71-L72) as it goes. Consequently the array storage type must be one that supports math.

I suspect the best way to solve this would be to create a new output array at the end, i.e., automatically apply `YCbCr.(img_YCbCr_half)` just as you are doing manually now. Is it better to "force" the extra conversion step on users or to require that they apply it manually, as you are doing now?

**Comment by johnnychen94** [comment]
what about provide a macro in `ColorTypes` 
```julia
@keep_colortype x |> foo |> bar # usage
convert.(eltype(x), x |> foo |> bar) # expansion
```

**Comment by johnnychen94** [comment]
Just found a much better solution taking advantages of `MappedArrays` together with in-place operation.

I don't have the time recently to dig into the structure of `ImageTransformations` to fix this, but I'll show a [code snippet](https://github.com/johnnychen94/ImageNoise.jl/blob/master/src/ApplyNoise/AdditiveWhiteGaussianNoise.jl) in `ImageNoise` that achieves the same goal, in case someone is interested in this:

```julia
function (n::AWGN)(out::AbstractArray{<:Number},
                   in::GenericGrayImage)
    out .= clamp01.(in .+ n.σ .* _rand(in) .+ n.μ) # inplace operation
end

for T in (AbstractGray, AbstractRGB)
    @eval function (n::AWGN)(out::AbstractArray{<:$T},
                             in::GenericImage)
        n(channelview(out), channelview(in))
    end
end

# Since generic Color3 aren't vector space, they are converted to RGB images
(n::AWGN)(out::AbstractArray{<:Color3},
         in::GenericImage) =
    n(channelview(of_eltype(RGB, out)), channelview(of_eltype(RGB, in)))
```

This outputs `Array{Lab}` for `Array{Lab}` since we don't create new arrays here.

**Comment by johnnychen94** [comment]
In response to https://github.com/JuliaImages/ImageTransformations.jl/issues/68#issuecomment-495909865

Unless we come up with a new way to handle `Array{Lab}`, it seems nothing needs to be done to improve the situation here; for performance consideration, it's the caller's responsibility to force type conversion on the result rather than the callee `restrict`.

For this reason, I'll just close this issue.
